spring:
  datasource:
    url: jdbc:mysql://localhost/cloud_vendor
    username: root
    password: Password123#@!

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
  jpa.hibernate.ddl_auto: create
